### PR TITLE
Update to NX 10

### PR DESCRIPTION
**Pull request by Jedidiah**
- Ran `nx migrate`
- Updated Gatsby version
- Added eslintFilePatterns argument to generateProjectLint as it is now required

### CODE REVIEW

**Comment by Jedidiah** [comment]
The tests pass and it builds without error but when running generate in a workspace I'm still getting `projectConfig.architect.lint.options.tsConfig is not iterable` after adding the paths to workspace.json

**Comment by Jedidiah** [comment]
Ah got the cause, [`generateProjectLint`](https://github.com/nrwl/gatsby/pull/28/files?file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.lock&file-filters%5B%5D=.ts#diff-30f5f4de24fdeb0251759f4986ff5c2817cea32f878387c3d7b8f2a21e01f74cR159) isn't returning tsConfig in the options.

I'll keep digging but I'm not familiar with the setup to know where that might be going wrong so if anyone has an idea let me know.

**Comment by Jedidiah** [comment]
Confirmed tested adding `architect.lint.options.tsConfig = [];` and is successfully generates the project including the tsConfig

**Comment by k4m4** [comment]
Any updates on this, @Jedidiah?

**Comment by jaysoo** [comment]
Hey @Jedidiah.
Thanks so much for your effort! I've gone ahead with the migration in #31 so we are good to go.

**Pull request closed without merging**
