### PR TITLE
chore: package updates

### PR DESCRIPTION
**Pull request by benpsnyder**
Update to the latest Nx

### CODE REVIEW

**Comment by benpsnyder** [comment]
@jaysoo could you process this PR ASAP as I'm having issues with NPM 7

**Comment by benpsnyder** [comment]
@jaysoo I apologize if this seems rude; I don't like to pressure. Hoping you get this notification and can approve this PR and publish to NPM. Thank you, sir!

**Comment by benpsnyder** [comment]
@vsavkin, @jaysoo, @FrozenPandaz - could someone kindly process this PR as soon as possible?  It's a simple fix of the version numbers that was overlooked previously. Thanks!

**Comment by jaysoo** [comment]
@benpsnyder Hi, sorry for the late reply. We've moved Gatsby plugin into the main monorepo so it'll be kept in sync with the other plugins moving forward.

**Comment by FrozenPandaz** [comment]
Closing this PR as this repo has been moved to https://github.com/nrwl/nx

**Pull request closed without merging**
